// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReceipeBlog.Model;

#nullable disable

namespace ReceipeBlog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ReceipeBlog.Model.FoodReceipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ReceipeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceipeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodReceipes");
                });

            modelBuilder.Entity("ReceipeBlog.Model.FoodReceipeIngredient", b =>
                {
                    b.Property<int>("FoodReceipeId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("FoodReceipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("FoodReceipeIngredients");
                });

            modelBuilder.Entity("ReceipeBlog.Model.Ingredients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("ReceipeBlog.Model.FoodReceipeIngredient", b =>
                {
                    b.HasOne("ReceipeBlog.Model.FoodReceipe", "FoodReceipe")
                        .WithMany("FoodReceipeIngredients")
                        .HasForeignKey("FoodReceipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReceipeBlog.Model.Ingredients", "Ingredients")
                        .WithMany("FoodReceipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodReceipe");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("ReceipeBlog.Model.FoodReceipe", b =>
                {
                    b.Navigation("FoodReceipeIngredients");
                });

            modelBuilder.Entity("ReceipeBlog.Model.Ingredients", b =>
                {
                    b.Navigation("FoodReceipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
